Launch cards
KnightHacks/admin-tool-frontend-2022 pull request #16
Opened 2022-09-08 00:14 UTC by ElijahMSmith

Added the cards to the /hackathon route that re-direct to other pages (event logistics, attendees, etc). Layout should be pleasant even on small screen sizes and the cards should wrap as needed.

2022-09-09 03:18 UTC, Victoria-Williamson requested changes
Looks pretty good; just a couple nit comments!

Also, I noticed a couple of minor UI issues with responsiveness and have some suggestions: 
- maybe make the card width a reusable size like md:w-1/3 for w-full. This way the cards should fill the width of the entire screen but also not be oddly small for phone-sized screens.
- add some padding onto the side of the page. 
- center the cards horizontally.

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/63255236/189264692-8e7ee513-6165-46b8-80d1-df901ed81726.png">

2022-09-09 03:18 UTC, Victoria-Williamson commented on src/components/hackathon/LaunchCard.tsx
> +export default function LaunchCard({ icon, text, onClick }: LaunchCardProps) {
nothing to revise, just noting I like how u took in the props. Never thought you could do it that way! I will definitely be stealing that

2022-09-09 03:18 UTC, Victoria-Williamson commented on src/pages/hackathon.tsx
> +import { ReactComponent as LogisticsIcon } from '../assets/logistics.svg';
nit: could you put all these new SVGs into assets/Hackathon/ pls? I've been organizing the rest like that cause without that the folder will probably have 20+ assets atm. Plus I don't think any of these components will get reused.

2022-09-09 22:26 UTC, conroyr41 approved these changes
Besides Victoria's suggestions, I think it looks good!

2022-09-09 23:27 UTC, ElijahMSmith commented
Not 100% happy with the reactivity changes for the info bar at the top (not the launch cards) but it looks good IMO at all breakpoints, just not when changing between them per-se. Suggestions welcome, or if we're good with it for now then great!

2022-09-19 00:55 UTC, Victoria-Williamson approved these changes
It looks really good thanks! :)

2022-09-19 03:46 UTC, merged