The Login Page!
KnightHacks/admin-tool-frontend-2022 pull request #52
Opened 2022-10-16 21:52 UTC by conroyr41

This is for issue #22.

Please note that I had an annoyingly hard time centering this page lol.

2022-10-23 20:29 UTC, Victoria-Williamson commented
I would suggest centering the login component vertically and adding some padding between the logo and the component itself.

2022-10-23 20:39 UTC, Victoria-Williamson requested changes

2022-10-23 20:39 UTC, Victoria-Williamson commented on src/pages/Login.tsx
> +            </div>
What is the purpose of this div, since there is nothing in it? ( the div with id="login-container" and the div with className="break")

2022-10-23 20:39 UTC, Victoria-Williamson commented on src/components/login/Login.css
> +#header-container {
Since this is empty remove it, as well as the id from the div that has it.

2022-10-23 20:39 UTC, Victoria-Williamson commented on src/pages/Login.tsx
> +            </div>
All of this should be a component, especially since its going to have to be connected to an endpoint later.

2022-11-01 21:21 UTC, Victoria-Williamson approved these changes
LGTM

2022-11-01 21:28 UTC, ElijahMSmith commented
Also LGTM!

2022-11-01 21:28 UTC, ElijahMSmith approved these changes

2022-11-01 22:22 UTC, merged