Sponsors page
KnightHacks/admin-tool-frontend-2022 pull request #55
Opened 2022-11-20 21:23 UTC by ElijahMSmith

Added table for organizing sponsors and a popup for editing or deleting sponsors.

Closes #23 and #24.

2022-11-28 22:03 UTC, LightBounded commented on src/models/sponsor.ts
> +export function getTierString(tier: SubscriptionTier) {
We can refactor these functions to be more simple.
`export enum SubscriptionTier {
  BRONZE = "bronze",
  SILVER = "silver",
  GOLD = "gold",
  PLATINUM = "platinum",
  INVALID = "invalid",
}

export function getTierString(tier: SubscriptionTier) {
  return tier.charAt(0).toUpperCase() + tier.slice(1);
}

export function getTierFromString(tier: string) {
  tier = tier.toLowerCase();
  return SubscriptionTier[tier];
}
`

2022-11-28 22:06 UTC, LightBounded submitted a review, later dismissed
Everything looks good, but we can simplify the way the SubcriptionTier enum is handled

2022-11-29 22:22 UTC, conroyr41 requested changes
I believe that the sponsors count should update according to the number of sponsors in the table. But right now it just shows as "0" even though the table is populated with mock data.

![image](https://user-images.githubusercontent.com/72236249/204661120-288663ea-6516-444c-a87b-ae90dc38658f.png)

2022-12-01 20:53 UTC, ElijahMSmith commented
> Everything looks good, but we can simplify the way the SubcriptionTier enum is handled

The code you're highlighting/fixing is from an old commit. That translation is not part of the most recent version of sponsor.ts and should be handled more elegantly now.

2022-12-01 20:55 UTC, ElijahMSmith commented
> I believe that the sponsors count should update according to the number of sponsors in the table. But right now it just shows as "0" even though the table is populated with mock data.
> 
> ![image](https://user-images.githubusercontent.com/72236249/204661120-288663ea-6516-444c-a87b-ae90dc38658f.png)

We can definitely do this, but right now this dummy data only exists in this component. I think we should wait until we have some of the API calls built in and have access to the hackathon data that we are viewing, which we can pass around to each page and to the header cards that display those statistics.

2022-12-08 17:12 UTC, conroyr41 approved these changes
Looks good!

2022-12-09 21:28 UTC, merged