The Hackathon Details Page
KnightHacks/admin-tool-frontend-2022 pull request #57
Opened 2022-12-11 17:07 UTC by conroyr41

Closes #26.

I created the UI for the hackathon details/settings page, which involved tweaking `InputGroup` and `SelectGroup` to allow for different element alignments/positions.

I wasn't sure what route to use for the new page, so for now, in order to navigate to the new page I created, there are 2 options:
1. From the Home page, click on the "Settings" button.
2. From the Home page, click on the "Go to Hackathon" button and then click on "Hackathon Settings" button.

I personally think that the "Edit Details" button is what should lead to the new page, however, we use the "/settings" route for **both** the "Settings" button on the Home page and the "Hackathon Settings" button on the Hackathon page. This may have been an error but I'm not sure. We should probably talk about it in a meeting.

2022-12-12 00:43 UTC, ElijahMSmith requested changes

2022-12-12 00:43 UTC, ElijahMSmith commented on src/components/InputGroup.tsx
> +		<div className={"w-full flex flex-col justify-start " + alignItems}>
This is fine, but we can simplify this to:

```<div className={"w-full flex flex-col justify-start " + (props.alignItems ?? "items-center")}>```

Then simply passing a string to override, whether that be "items-start" or something else, and deleting the alignItems variable. Same goes for SelectGroup.tsx!

Might also be a good idea to include the justify in here as well so we can position wherever and however in the future.

2022-12-12 01:31 UTC, conroyr41 commented
Note: We decided during a meeting today (12/11) that we would hide both the "Edit Details" and "Settings" buttons on the Home Page, and hide both the "Event Logistics" and "Hackathon Settings" buttons on the Hackathon page. I will make those adjustments soon!

2022-12-18 16:43 UTC, ElijahMSmith approved these changes

2022-12-18 16:43 UTC, merged